### ISSUE TITLE
feature request: layers

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#12]
You can get magnificent effects by using multiple B.Schaffl's in series.
For example one with a little regular shuffle, one with an uneven number of steps for a little polyrythmic dynamic variation and one with a 1 beat length and the middle STR slider dragged a bit left, for a pushed feel, or dragged right for a laid back feel. 

It would be  very handy if you could do that all in one plugin and save it all as one preset.
I'm imagining tabs like in B.Shapr and inside each tab would be a complete instance of B.Schaffl as it is now.

I've been experimenting with this for a while now, and for me this feature would also fix #10, as you can quickly and easily add true human like variation, in a controlled manner.

The amount controls from #11 would be great to have both per layer and for the whole plugin

Here is a small Ardour 6 session, that hopefully demonstrates the usefulness of multiple instances in series: 

[BSchafflSeries.zip](https://github.com/sjaehn/BSchaffl/files/4831091/BSchafflSeries.zip)
.
I don't know if a-Fluidsynth uses absolute or relative paths.
You might have to set the instrument to ``/path/to/BSchafflSeries/Instruments/industrializer/industrializer.sf2``
This instrument has lots of different samples on different velocity layers, so nicely demonstrates the subtle dynamics.

**Comment by sjaehn** [comment]
Honestly, I experienced a lot of problems with B.Shapr's multiple shapes.

Problem 1:
Each shape almost needs the complete set of controllers. The easiest way to implement controllers are the LV2 control ports. But you have pre-define all ports you maybe will need. No creation of ports on the fly. And we have already > 60 control ports in B.Schaffl with one layer. Times the max. number of layers. The higher the number of controllers the trickier for the user to access to the controllers (e. g., via automation).

Problem 2:
Latency. It's now the job of the plugin to handle latency between the layers. And this can be tricky too. This is the main reason why progression of development for B.Shapr slowed down.

Problem 3:
Usability. Too many layers may make it complicated. And difficult to understand what's going on inside the plugin. Especially in combination with latency. Multiple instances of a plugin instead of multiple layers may communicate this in a clearer way. But anyway, do you fully understand your BSchafflSeries demo?

**Comment by magnetophon** [comment]
Those are good points, unfortunately.  ;)

1) You could make less parameters automate-able. I'm not sure I like that idea though...
2) I was hoping it would make it easier for you to get the visuals in time, at least compared to multiple instances.
3) I wouldn't say I fully understand it, but I think understanding the individual parameters and hearing the effects is enough to be able to use a plugin.

I hope one day someone will come up with solutions somehow!   :)
