### ISSUE TITLE
Feature request: level before timing.

### ISSUE THREAD

**Issue by magnetophon** [sjaehn/BSchaffl#7]
From my experimentation, it seems the notes are first moved in time and then the plugin looks which step they fall under.
I would expect it to work the other way around, so that I can change the timing of a pattern over the course of a song, but still have the same notes accentuated.
It also makes it easier to predict what the plugin will do to your notes.

If you want to go all out, you could make it configurable, but that's not an important feature, imho.

**Comment by sjaehn** [comment]
> From my experimentation, it seems the notes are first moved in time and then the plugin looks which step they fall under.

Yes, if you quantize. But quantization is only a correction, as we discussed before. The movement (step stretch) itself happens *after* the step assignment.

There is a linear algorithm/workflow:
1. MIDI in (note or anything else)
2. Assign and/or fit to the input step pattern (smart quantization)
3. Signal amplification (step amp sliders)
4. Move / time stretch (str markers)
5. MIDI out 

> I would expect it to work the other way around, so that I can change the timing of a pattern over the course of a song, but still have the same notes accentuated.

The plugin exactly *should* do this. Otherwise it's a bug?

**Comment by magnetophon** [comment]
I was mishearing, same thing as in https://github.com/sjaehn/BSchaffl/issues/6
